### ISSUE TITLE
Let 'kDefaultTimeout' is private and cannot be referenced from a default argument value.

### ISSUE THREAD

**Issue by burakgunduztr** [lyft/Kronos#20] opened 2017-06-07 09:22 UTC
After conversion to Swift 4 getting this error in the DNSResolver.swift - Kronos pod.

<img width="1547" alt="issue" src="https://user-images.githubusercontent.com/13763935/26871387-a0df0e12-4b7b-11e7-8a32-09ea8835de51.png">

Edit: Also same in NTPClient.swift

**Comment by keith** [comment] 2017-06-07 16:55
Yep, this is a [bug in Swift](https://bugs.swift.org/browse/SR-5111) caused by `ENABLE_TESTABILITY = YES`. It should be fixed [soon](https://twitter.com/slava_pestov/status/872282746072162304).

In the meantime I've pushed the `swift-4` branch with a workaround. We'll try to keep it updated through the beta period.

**Closed** 2017-09-19 05:45 UTC
